### ISSUE TITLE
JNE BELUM ADA, JNT EROR

### ISSUE THREAD

**Issue by bagusok** [rapdodge/API-Pengiriman#1]
Jne belum didukung, sama jnt gabisa

**Comment by rapdodge** [comment]
- Untuk JNE, memang saat ini sudah tidak didukung kembbali, karena mereka mengubah API mereka
- Untuk JNT, akan saya cek nanti, saat ini saya terlalu sibuk :)

Terima kasih telah menggunakan skrip PHP API-Pengiriman ini!

**Comment by rapdodge** [comment]
Menyerah untuk ambil API dari JNE
API JNT juga tidak berfungsi sebagaimana mestinya

Kasus ditutup.
